version: '3'
services:
  app:
    build: ./app
    command: gunicorn app.wsgi:application -b 0.0.0.0:8000
    working_dir: /usr/src/app/
    expose:
      - "8000"
    env_file:
      - ./.env.development
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    networks:
      - front
      - back
  db:
    image: postgres:12.0-alpine
    env_file:
      - ./.env.development
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - back
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - app
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    networks:
      - front

volumes:
  db_data:
  static_volume:
  media_volume:

networks:
  front:
    external: false
  back:
    external: false
